# Generated by Django 3.1.7 on 2021-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210304_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.TextField(default=2020, max_length=20),
            preserve_default=False,
        ),
    ]
