# Generated by Django 3.1.7 on 2021-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210304_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Physics', 'Physics'), ('bp', 'bp')], default='', max_length=100),
        ),
    ]
