# Generated by Django 3.1.7 on 2021-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210306_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('bp', 'bp')], default='', max_length=100),
        ),
    ]
