# Generated by Django 3.1.7 on 2021-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='vids',
            field=models.FileField(upload_to='medias'),
        ),
    ]
