# Generated by Django 3.1.7 on 2021-03-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_delete_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
