# Generated by Django 3.1.7 on 2021-03-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210306_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
    ]
