# Generated by Django 3.1.7 on 2021-03-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solutionfiles',
            field=models.FileField(default='', upload_to='medias/solutions'),
        ),
    ]
