# Generated by Django 3.1.7 on 2021-03-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_remove_solution_solutionfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='questionfiles',
            field=models.FileField(default='', upload_to='medias/questions'),
        ),
    ]
