# Generated by Django 3.1.7 on 2021-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_assignment_solutionfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emailaddress',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
