# Generated by Django 3.1.7 on 2021-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_userprofile_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emailaddress',
            field=models.CharField(default='', max_length=60),
        ),
    ]
