# Generated by Django 3.1.7 on 2021-03-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20210307_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emailaddress',
        ),
    ]
