# Generated by Django 3.1.7 on 2021-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_remove_userprofile_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='solutionfiles',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='questionfiles',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.CharField(default='', max_length=500, verbose_name=('bp', 'bp')),
        ),
    ]
